name: Build and Push

on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - uses: docker/build-push-action@v5
              with:
                push: true
                tags: |
                  ghcr.io/${{ github.repository }}:latest
                  ghcr.io/${{ github.repository }}:${{ github.sha }}
            
            - name: Update image tag in k8s-manifests
              env:
                MANIFESTS_PAT: ${{ secrets.MANIFESTS_PAT }}
              run: |
                git clone https://jaime-carbo:${MANIFESTS_PAT}@github.com/jaime-carbo/k8s-manifests.git manifests
                cd manifests
                sed -i "s|image: ghcr.io/jaime-carbo/olas:.*|image: ghcr.io/jaime-carbo/olas:${{ github.sha }}|" apps/first-app.yaml
                git config user.name "github-actions"
                git config user.email "github-actions@github.com"
                git add apps/first-app.yaml
                git commit -m "Update demo-api to ${{ github.sha }}"
                git push